### ISSUE TITLE
187/2018 - Obbligatorietà dei dati

### ISSUE THREAD

**Issue by AndreaLugli** [SocialCities/FaWooLoSo#4]
Buongiorno!

Purtroppo quando si sceglie il tipo di documento fattura appare come obbligatorio a livello grafico il codice fiscale con asterisco. Gli utenti devono compilare almeno 1 dei 2 campi, si potrebbe rendere obbligatorio con l'asterisco solo "Tipo Documento" inserendo una riga di testo che avvisi l'utente che deve inserire almeno 1 dei 2 campi?

Nel tipo di documento ricevuta il nostro commercialista ci ha sottolineato che il codice fiscale non è obbligatorio, inoltre ci alleggerirebbe il processo di acquisto. Pensate sia una cosa che possiamo sistemare?

Vi ringrazio per la vostra professionalità

Fabio

**Comment by AndreaLugli** [comment]
- [ ] Admin sceglie se: codice fiscale obbligatorio in ricevuta

**Comment by DanielaGenerali** [comment]
Admin sceglie se: codice fiscale obbligatorio in ricevuta.
Default: codice fiscale obbligatorio.
